# Generated by Django 2.2.7 on 2020-03-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0008_auto_20200302_0759'),
        ('submission', '0010_auto_20200315_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_file', models.CharField(max_length=64)),
                ('dest_file', models.CharField(max_length=64)),
                ('percentage', models.FloatField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity', to='competition.Competition')),
                ('dest_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_sub', to='submission.Submission')),
                ('src_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_sub', to='submission.Submission')),
            ],
        ),
    ]
