# Generated by Django 2.2.7 on 2020-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
