# Generated by Django 2.2.7 on 2020-02-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0003_auto_20200216_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.FileField(upload_to='')),
                ('valid', models.BooleanField()),
                ('filtered', models.BooleanField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Participant')),
            ],
        ),
    ]
