# Generated by Django 2.2.7 on 2020-02-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='valid',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='未提交', max_length=32),
            preserve_default=False,
        ),
    ]
