# Generated by Django 2.2.7 on 2020-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200217_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='未提交', max_length=32),
        ),
    ]
