# Generated by Django 2.2.7 on 2020-02-18 01:10

import apps.submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20200217_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='filtered',
        ),
        migrations.AddField(
            model_name='submission',
            name='filtered_bundle',
            field=models.FileField(default='', upload_to=apps.submission.models.filtered_bundle_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='bundle',
            field=models.FileField(upload_to=apps.submission.models.origin_bundle_path),
        ),
    ]
