# Generated by Django 2.2.7 on 2020-02-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20200218_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
