# Generated by Django 2.2.7 on 2020-02-25 01:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20200225_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bundle_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='missing_files',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
