# Generated by Django 2.2.7 on 2020-02-25 02:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20200225_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='bundle_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
