# Generated by Django 2.2.7 on 2020-03-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_remove_submission_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_submission', to='competition.Participant'),
        ),
    ]
