# Generated by Django 2.2.7 on 2020-04-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20200315_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='valid',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='未收到提交', max_length=64),
        ),
    ]
