# Generated by Django 2.2.7 on 2020-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20200408_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='已提交，校验中..', max_length=64),
        ),
    ]
