# Generated by Django 2.2.7 on 2020-02-14 02:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submission_standard',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'tes': 'test'}),
            preserve_default=False,
        ),
    ]
