# Generated by Django 2.2.7 on 2020-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_submission_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
