# Generated by Django 2.2.7 on 2020-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20200216_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='pid',
        ),
        migrations.AddField(
            model_name='participant',
            name='pno',
            field=models.CharField(default='test', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
