# Generated by Django 2.2.7 on 2020-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20200220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='grade',
            field=models.CharField(default='senior', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='id_num',
            field=models.CharField(default='null', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='province',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='school',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
