# Generated by Django 2.2.7 on 2020-02-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20200220_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
    ]
