# Generated by Django 2.2.7 on 2020-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_remove_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_num',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pno',
            field=models.CharField(max_length=64),
        ),
    ]
