# Generated by Django 2.2.7 on 2020-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20200302_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submission_path',
            field=models.CharField(default='/xxx/yyy', max_length=64),
        ),
        migrations.AddField(
            model_name='participant',
            name='host',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
