# Generated by Django 2.2.7 on 2020-04-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20200325_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='pos_x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='pos_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
