# Generated by Django 2.2.7 on 2020-04-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_auto_20200410_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='participant',
            name='position',
            field=models.CharField(default='0-0', max_length=16),
            preserve_default=False,
        ),
    ]
