# Generated by Django 2.2.7 on 2020-04-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20200410_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
