# Generated by Django 2.2.7 on 2020-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20200410_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('layout_matrix', models.CharField(max_length=512)),
            ],
        ),
    ]
