# Generated by Django 2.2.7 on 2020-04-14 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_roomlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='room_layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='competition.RoomLayout'),
            preserve_default=False,
        ),
    ]
