# Generated by Django 2.2.7 on 2020-04-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_competition_room_layout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomLayout',
            new_name='Room',
        ),
    ]
