# Generated by Django 2.2.7 on 2020-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_auto_20200424_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='submission_path',
            field=models.CharField(max_length=64),
        ),
    ]
